name: Eslint 
on:
  pull_request:
    branches:
      - master
jobs:
  eslint:
    name: eslint
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Eslint
        run: yarn --cwd ./frontend/app run lint

