name: Build 
on:
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Build 
        run: CI=false yarn --cwd ./frontend/app run build

