name: Prettier 
on:
  pull_request:
    branches:
      - master
jobs:

  prettier:
    name: prettier
    runs-on:
      - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn --cwd ./frontend/app install
      - name: Prettier 
        run: CI=false yarn --cwd ./frontend/app run prettier:check 

